# Generated by Django 5.2.5 on 2025-08-20 15:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('destination_type', models.CharField(choices=[('hill_station', 'Hill Station'), ('beach', 'Beach'), ('historical', 'Historical'), ('religious', 'Religious'), ('adventure', 'Adventure'), ('wildlife', 'Wildlife'), ('city', 'City')], max_length=20)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=200)),
                ('average_temperature', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='State code like MH, DL, etc.', max_length=10, unique=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='states/')),
                ('popular_destinations', models.TextField(blank=True, help_text='Comma separated popular destinations')),
                ('best_time_to_visit', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('car', 'Car'), ('flight', 'Flight'), ('cruise', 'Cruise'), ('bike', 'Bike')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Travel Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TravelClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('class_type', models.CharField(choices=[('economy', 'Economy/Lower Class'), ('standard', 'Standard/Middle Class'), ('business', 'Business Class'), ('first', 'First Class'), ('luxury', 'Luxury/Upper Class'), ('premium', 'Premium Luxury')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.TextField(blank=True, help_text='Comma separated amenities')),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier for base price', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Travel Classes',
                'ordering': ['price_multiplier'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hotel_type', models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('villa', 'Villa'), ('hostel', 'Hostel'), ('homestay', 'Homestay'), ('apartment', 'Apartment'), ('camp', 'Camp')], max_length=20)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
                ('star_rating', models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('description', models.TextField()),
                ('amenities', models.TextField(blank=True, help_text='Comma separated amenities')),
                ('check_in_time', models.TimeField(default='14:00:00')),
                ('check_out_time', models.TimeField(default='12:00:00')),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('has_spa', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_restaurant', models.BooleanField(default=True)),
                ('wifi_available', models.BooleanField(default=True)),
                ('parking_available', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('website', models.URLField(blank=True)),
                ('average_price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='Masters.destination')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_occupancy', models.IntegerField(default=2)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.TextField(blank=True)),
                ('size', models.CharField(blank=True, help_text='Room size in sq ft', max_length=50)),
                ('bed_type', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='Masters.hotel')),
            ],
            options={
                'ordering': ['base_price'],
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='Masters.state'),
        ),
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('agency_type', models.CharField(choices=[('local', 'Local Operator'), ('national', 'National Operator'), ('international', 'International Operator')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.state')),
            ],
            options={
                'verbose_name_plural': 'Travel Agencies',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together={('name', 'state')},
        ),
    ]
