# Generated by Django 5.2.5 on 2025-09-10 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['destination_type'], name='Masters_des_destina_02b373_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_popular'], name='Masters_des_is_popu_22f578_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['hotel_type'], name='Masters_hot_hotel_t_af44a9_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['star_rating'], name='Masters_hot_star_ra_ee71cf_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtype',
            index=models.Index(fields=['is_available'], name='Masters_roo_is_avai_8c0534_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['code'], name='Masters_sta_code_85149a_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country'], name='Masters_sta_country_a278b1_idx'),
        ),
        migrations.AddIndex(
            model_name='travelagency',
            index=models.Index(fields=['agency_type'], name='Masters_tra_agency__baf830_idx'),
        ),
        migrations.AddIndex(
            model_name='travelagency',
            index=models.Index(fields=['is_verified'], name='Masters_tra_is_veri_abdb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='travelcategory',
            index=models.Index(fields=['category_type'], name='Masters_tra_categor_764962_idx'),
        ),
        migrations.AddIndex(
            model_name='travelclass',
            index=models.Index(fields=['class_type'], name='Masters_tra_class_t_b6e2c4_idx'),
        ),
        migrations.AddField(
            model_name='destinationtransport',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.travelcategory'),
        ),
        migrations.AddField(
            model_name='destinationtransport',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_options', to='Masters.destination'),
        ),
        migrations.AddField(
            model_name='destinationtransport',
            name='travel_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.travelclass'),
        ),
        migrations.AddIndex(
            model_name='destinationtransport',
            index=models.Index(fields=['category'], name='Masters_des_categor_0a7992_idx'),
        ),
        migrations.AddIndex(
            model_name='destinationtransport',
            index=models.Index(fields=['destination'], name='Masters_des_destina_b65ef3_idx'),
        ),
    ]
