# Generated by Django 4.2.7 on 2025-11-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_destinationtransport_alter_hotel_star_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
