# Generated by Django 4.2.7 on 2025-11-17 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_alter_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 18, 33, 27, 685245, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 18, 33, 27, 697173, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 18, 33, 27, 685245, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='travelagency',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 18, 33, 27, 695361, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='travelcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 18, 33, 27, 685245, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='travelclass',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 18, 33, 27, 695361, tzinfo=datetime.timezone.utc)),
        ),
    ]
