# Generated by Django 5.2.5 on 2025-08-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_itineraryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripplan',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
