# Generated by Django 5.2.5 on 2025-08-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_tripplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplan',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
