# Generated by Django 5.2.5 on 2025-09-10 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_destinationtransport_alter_hotel_star_rating_and_more'),
        ('trips', '0004_tripplan_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_checked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TripPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.TextField(blank=True, help_text='Comma-separated: beach, adventure, culture')),
                ('budget_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Trip Preferences',
            },
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='tripplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='ai_confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='is_ai_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itineraryitem',
            name='persons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tripinvoice',
            name='invoice_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tripinvoice',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='Masters.destination'),
        ),
        migrations.AlterField(
            model_name='tripplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='itineraryitem',
            index=models.Index(fields=['trip'], name='trips_itine_trip_id_90c803_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryitem',
            index=models.Index(fields=['date'], name='trips_itine_date_dc301b_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryitem',
            index=models.Index(fields=['type'], name='trips_itine_type_8c5e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='tripplan',
            index=models.Index(fields=['user'], name='trips_tripp_user_id_fa42eb_idx'),
        ),
        migrations.AddIndex(
            model_name='tripplan',
            index=models.Index(fields=['destination'], name='trips_tripp_destina_f59358_idx'),
        ),
        migrations.AddIndex(
            model_name='tripplan',
            index=models.Index(fields=['status'], name='trips_tripp_status_dc7f4e_idx'),
        ),
        migrations.AddField(
            model_name='packingitem',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='trips.tripplan'),
        ),
        migrations.AddField(
            model_name='trippreference',
            name='travel_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Masters.travelclass'),
        ),
        migrations.AddField(
            model_name='trippreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
