# Generated by Django 4.2.7 on 2025-12-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='redirect_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
